/****** Object:  Table [dbo].[AsyncUploadImages]    Script Date: 2/20/2014 1:22:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AsyncUploadImages](
	[ImageID] [int] IDENTITY(1,1) NOT NULL,
	[ImageData] [varbinary](max) NOT NULL,
	[ImageName] [nvarchar](100) NOT NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_AsyncUploadImages] PRIMARY KEY CLUSTERED 
(
	[ImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


